### ISSUE TITLE
Trying to install and it gives me an error

### ISSUE THREAD

**Issue by johnthescienceguy** [gadomski/sbd#3]
Pete

I am an old guy who is a rookie but I am trying to install your SBD iridium and I am getting that the repository does't exist when I run

pip install git+https://github.com/gadomski/sbd@master

I get fatal error repository not found.  Maybe my user name and password don't give me access.  Is this available for public access?

**Comment by gadomski** [comment]
Hm, it's a public repository, so I don't know why you're getting a "not found". Can you do a:

```bash
git clone https://github.com/gadomski/sbd
```

If you don't have git, that could be a problem.

FYI this python repository is no longer maintained...I now work from https://github.com/gadomski/sbd-rs. I'll put a note in the README here about that.

**Comment by johnthescienceguy** [comment]
Yup I did the git clone and it worked.  thanks.

I will look at the rust implementation.  thanks for the heads up.
